### ISSUE TITLE
Document Fix Request

### ISSUE THREAD

**Issue by Debabilizer** [MicrosoftDocs/OfficeDocs-ProjectServer#1]
This page has the links mixed up. 2013 link to 2016 and 2016 link to 2013.
More on premise please. It is to bad MS is focused on diminishing on premise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e704c1-9054-ae27-58ac-8445bc88bdee
* Version Independent ID: 488f11d5-373f-788b-0a73-697c553a8b32
* Content: [Install and configure for Project Server | Microsoft Docs](https://docs.microsoft.com/en-us/Project/install-and-configure-for-project-server-2016)
* Content Source: [Project/install-and-configure-for-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/install-and-configure-for-project-server-2016.md)
* Service: **unspecified**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Thanks for the feedback on the links.  I updated the links and they should work now. Thanks again!
