### ISSUE TITLE
Powershell Instructions for these manual ?

### ISSUE THREAD

**Issue by josepcanas** [MicrosoftDocs/OfficeDocs-ProjectServer#10]
Can you please share powershell instructions to perform this actions ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88e71a4-f3d9-045a-d3cf-878b9d375f07
* Version Independent ID: fa6cd963-95ea-d077-ba32-35396e64df3a
* Content: [Add Project Online to a site collection](https://docs.microsoft.com/en-us/projectonline/add-project-online-to-a-site-collection)
* Content Source: [ProjectOnline/add-project-online-to-a-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/add-project-online-to-a-site-collection.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@josepcanas Thank you for this feedback

I agree the PowerShell instructions should be included in this article. 

I was able to get this into the backlog for the PowerShell team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by lindspea** [comment]
@josepcanas Hi Jose, we are working towards getting the instructions added as soon as possible. I will let you know once the issue has been resolved.

**Comment by efrene** [comment]
Hi Jose, 
While PowerShell cmdlets exist for doing this for Project Server, I am sorry to say that Office 365 PowerShell cmdlets do not exist to do this for Project Online.  Sorry for the inconvenience.
Efren
