### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pascalito80** [MicrosoftDocs/OfficeDocs-ProjectServer#11]
Link to "Upgrade to Project Server 2019 Public Preivew" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e704c1-9054-ae27-58ac-8445bc88bdee
* Version Independent ID: 488f11d5-373f-788b-0a73-697c553a8b32
* Content: [Install and configure for Project Server](https://docs.microsoft.com/en-us/Project/install-and-configure-for-project-server-2016)
* Content Source: [Project/install-and-configure-for-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/install-and-configure-for-project-server-2016.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@pascalito80 Thank you for catching this

I will make sure this gets corrected. 

I was able to get this into the backlog for the Project Server team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by efrene** [comment]
Thanks for noting this too us!  I removed the references to "public preview' and verified that the link was correct.  Many thanks!
