### ISSUE TITLE
OUT OF DATE

### ISSUE THREAD

**Issue by hankanman** [MicrosoftDocs/OfficeDocs-ProjectServer#120]
The version release notes on this page are out of date by over a year, the solution has just prompted for a new version today of 1.0.11.162 much further on than the article lists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a801175-de35-1beb-b061-f87d8ff1ef94
* Version Independent ID: 943295ec-36af-81f2-869f-6478228c41d4
* Content: [Project Service Core solution version history - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/project-service-core-solution-version-history)
* Content Source: [ProjectWeb/project-service-core-solution-version-history.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/project-service-core-solution-version-history.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @hankanman, thank you for your feedback.

@stsporen could you kindly help here? Thanks!

**Comment by joshbooker** [comment]
it'd be nice to know what's new in the release notes.  this article is approaching 2 years out of date #133

**Comment by dariomws** [comment]
@stsporen @serdars, could you kindly help here? Thanks!

**Comment by stsporen** [comment]
@dariomws We need to pull this area from the documentation. The updates are published over here: https://docs.microsoft.com/en-us/dynamics365/project-operations/pro/whats-new/whats-new-2021-early-access-lite

**Comment by joshbooker** [comment]
@stsporen, is it correct to say this article's purpose is to help Project-for-the-web admins differentiate the subset of whats changed in the project service core solution applicable to P4W versus the entire 'what new' release wave for Dyn365PO?  

FWIW,  from the P4W side, we're having a hard time knowing where the lines are drawn.
Thanks for listening.

**Comment by dariomws** [comment]
@stsporen,

Could we pull this area from the documentation?

**Comment by scanum** [comment]
@stsporen following up on Dario's question. Thanks!

**Comment by dariomws** [comment]
@stsporen,

Could we pull this area from the documentation?
