### ISSUE TITLE
App Not available

### ISSUE THREAD

**Issue by Online24x7** [MicrosoftDocs/OfficeDocs-ProjectServer#13]
as per step 3 In the SharePoint Store, search for Office 365 Project Portfolio Dashboard.

app is not available please help in getting that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd3a37e-4d30-4f74-4b9a-1e1ed95b0a0b
* Version Independent ID: 6e104a98-accf-f86e-54e1-77f224e07af3
* Content: [Configure Office 365 Project Portfolio Dashboard](https://docs.microsoft.com/en-us/projectonline/configure-office-365-project-portfolio-dashboard)
* Content Source: [ProjectOnline/configure-office-365-project-portfolio-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/configure-office-365-project-portfolio-dashboard.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@Online24x7 Thank you for this feedback

I am not sure why the Office 365 Project Portfolio Dashboard isn't in the SharePoint Store. I want to make sure this is documented and addressed promptly. Support can handle this to resolution and in a quick manner. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by buildbod** [comment]
The Office 365 Project Portfolio Dashboard is still not available in the SharePoint store
