### ISSUE TITLE
Misinformation...

### ISSUE THREAD

**Issue by AdrianJe** [MicrosoftDocs/OfficeDocs-ProjectServer#134]
The article has the following Note:

_You will only be able to view the project file. You will not be able to edit the .MPP file in any way. You cannot export the .MPP file from Project for the web and import it into Project Online (PWA).__

In my option, this makes no sense at all and it’s really not true. It almost seems like a FUD (fear, uncertainty, doubt) statement to try to discourage users from going back to Project Online or something like that.  Project can open the MPP file, you can edit it, you can save it and you can save it to a server. Though the MPP file has additional storages such as TBkndAttachment, TBkndConversation, and TBkndCheckListItem, Project, even if it doesn’t know what these storages are, knows how to handle them. This is no different in how Project 2010, 2013 and 2016 know how to open and handle MPP files created by a C2R subscription version.  If there’s really some concern that there’s something “wrong” with the MPP file, the XML file can be used and saved to an MPP file. The export process actually loads the MPP file into Project and does a SaveAs to generate the XML file and so if there’s some concern about “stuff that Project may not know about” then the XML file will be as pure as you can get because it won’t carry over any of the “extra” stuff.

Overall, the Note seems like a needless statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c839da-0f06-c409-9744-4d285e405dbb
* Version Independent ID: 161f4096-13a0-1368-bdbd-0e530bcffbf0
* Content: [Export user data from Project for the Web - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/export-user-data-from-project-for-the-web)
* Content Source: [ProjectWeb/export-user-data-from-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/export-user-data-from-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @AdrianJe, thank you for your feedback.

I think the information in the note is related to the Web version and you are talking about the desktop client. Am I right?

**Comment by tiburd** [comment]
Closing this issue.
@dariomws @scanum
