### ISSUE TITLE
Confusing SKU names

### ISSUE THREAD

**Issue by jjohnson623** [MicrosoftDocs/OfficeDocs-ProjectServer#138]
[Enter feedback here]
FYI I am a field MSFT employee (jasjohns) and this is not an issue with the documentation specifically, but with the naming of the different versions of the Project for Office SKU.  In commercial it is 'Project for Office (xxxx)' which makes it easy to explain that this is essentially a Project viewer license, attached to the Office suite.  Simple and self explanatory by the name.  On the other hand the GCC SKU's are listed as 'Project for Government (xxxx)' which really sounds like this is a license for MS Project for Government customers and not a fancy file viewer feature from the Office suite.  Can we provide feedback to the commerce team to review the naming and perhaps change the GCC names to 'Project for Office GCC (xxxx)' for both consistency and clarity?

FYI here is the customer query that brought this to my attention:

"I’m starting to apply our new G5 licenses to our users and I noticed that it shows Microsoft Project G5 as one of the options. Do these new licenses include the full version of Project."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cb77235-cf69-559b-efd8-07015dfaf542
* Version Independent ID: 431b037e-2b1d-f221-5195-8e7b979c3569
* Content: [Office 365 User view access to Project for the web and Roadmap - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/office-365-user-view-access-to-project-and-roadmap)
* Content Source: [ProjectWeb/office-365-user-view-access-to-project-and-roadmap.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/office-365-user-view-access-to-project-and-roadmap.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
