### ISSUE TITLE
PS 2016 page is actually a copy of the 2019 page

### ISSUE THREAD

**Issue by audimoose** [MicrosoftDocs/OfficeDocs-ProjectServer#14]
Can we get this fixed, so we can access the 2016 content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f75d4da-bb0a-ecc6-5431-96a3109e6f25
* Version Independent ID: d88087f9-9633-db07-7e84-b2f37f811c05
* Content: [What's new for IT pros in Project Server 2019 Public Preview](https://docs.microsoft.com/en-us/project/what-s-new-for-it-pros-in-project-server-2016)
* Content Source: [Project/what-s-new-for-it-pros-in-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/what-s-new-for-it-pros-in-project-server-2016.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@audimoose Thank you for this feedback. 

We appricate you pointing this out to us. I will make sure that this issue of the 2016 page being a copy of the 2019 page gets in front of the ProjectServer team so it can be corrected. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by efrene** [comment]
Thanks for noting this to us. Fixed.
