### ISSUE TITLE
Documentation not clarifying the license requirement

### ISSUE THREAD

**Issue by arnavDamco** [MicrosoftDocs/OfficeDocs-ProjectServer#140]
If the user already has  Project online license but wants to customize the managed solution by adding a few screens or adding a BPF, would they need a Powerapps license for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aded6f80-71b5-2e58-8a39-d1ec2f69443a
* Version Independent ID: aded6f80-71b5-2e58-8a39-d1ec2f69443a
* Content: [Deploy the Project Management Office Accelerator - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/deploy-project-for-web-accelerator-power-bi-template)
* Content Source: [ProjectWeb/deploy-project-for-web-accelerator-power-bi-template.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/deploy-project-for-web-accelerator-power-bi-template.md)
* Service: **project-web**
* GitHub Login: @v-stthomas
* Microsoft Alias: **v-stthomas**

**Comment by dariomws** [comment]
Hi @arnavDamco, thank you for your feedback.

I'm not sure if I understand your request. But to deploy the PMO Accelerator the requirement is to have the "rights to create Power Automate flows using the Common Data Service connector".

From the other article, you require Power Automate or Power Apps premium.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
