### ISSUE TITLE
Power BI Template Report Download Not Working

### ISSUE THREAD

**Issue by JJGriffin** [MicrosoftDocs/OfficeDocs-ProjectServer#141]
Currently, the download link for the Power BI template report is not working - instead, a 404 - Content Not found error is returned via the following hyperlink:

https://docs.microsoft.com/en-us/OfficeDev/Project-Accelerator#heres-the-latest-version-of-the-power-bi-template-for-the-accelerator

![image](https://user-images.githubusercontent.com/24753554/182813184-8d3f1d7b-c93c-40e0-b944-434aad510bb6.png)

Is it possible to please fix this so that the template report can be downloaded successfully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3665e0dd-7d6c-b592-e4bc-b591334fbc14
* Version Independent ID: 3665e0dd-7d6c-b592-e4bc-b591334fbc14
* Content: [Add the Power BI template to the Project Management Office Accelerator - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/deploy-power-bi-template-project-for-web-accelerator)
* Content Source: [ProjectWeb/deploy-power-bi-template-project-for-web-accelerator.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/deploy-power-bi-template-project-for-web-accelerator.md)
* Service: **project-web**
* GitHub Login: @v-stthomas
* Microsoft Alias: **v-stthomas**

**Comment by dariomws** [comment]
Hi @JJGriffin, thank you for your feedback.

Could you try the link again? It's working for me; it should redirect you to a GitHub repository.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
