### ISSUE TITLE
The GlobalAssemblyCache can't be found on this object

### ISSUE THREAD

**Issue by ddarnley** [MicrosoftDocs/OfficeDocs-ProjectServer#145]
When running the command ExportProjectContent I am getting an error stating the globalseemblycache can't be found on this object. 

https://docs.microsoft.com/en-us/project-for-the-web/export-user-data-from-project-for-the-web#feedback

**Comment by dariomws** [comment]
@ddarnley - thank you for submitting feedback. 

I think the best way forward is if you open a service ticket so this can get resolved ASAP. Please keep us posted here on the resolution to feed whatever information you discover into the content.
