### ISSUE TITLE
Generic Resource Not Available for Assignment

### ISSUE THREAD

**Issue by Trassin** [MicrosoftDocs/OfficeDocs-ProjectServer#146]
I followed the guide and was able to add a Generic Resource within Power Apps ---> Project. However, the Generic Resource is still not showing as an option to be added to the P4W team. Is there a wait time to allow for it to populate to P4W as an option to be added? 

As a note, my organization does not use Dynamics 365, so we don't have access to the full suite of resource planning/scheduling tools. I am just working with P4W.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 447f59e5-5797-453e-1104-8645a39230a6
* Version Independent ID: f7400ea9-2c87-d96a-6cd4-3b1882372e4e
* Content: [Add non-user resources in Project for the web - Project for the web](https://learn.microsoft.com/en-us/project-for-the-web/create-nonuser-resources-in-project-for-the-web)
* Content Source: [ProjectWeb/create-nonuser-resources-in-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/create-nonuser-resources-in-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
@Trassin - thank you for submitting feedback. 

I think the best way forward is if you open a service ticket so this can get resolved ASAP. Please keep us posted here on the resolution to feed whatever information you discover into the content.
