### ISSUE TITLE
Brazil is on the list twice

### ISSUE THREAD

**Issue by hocull** [MicrosoftDocs/OfficeDocs-ProjectServer#15]
Brazil and Portuguese (Brazil) are both listed with the same ll-cc and lcid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ace414fa-9f77-28e5-03c7-489dca967c66
* Version Independent ID: b4bb50da-07f8-f665-5134-56b85e9276dd
* Content: [Supported languages for Project Online](https://docs.microsoft.com/en-us/projectonline/supported-languages-for-project-online)
* Content Source: [ProjectOnline/supported-languages-for-project-online.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/supported-languages-for-project-online.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@hocull Thank you for this feedback

We apricate you pointing this out to us. I will get this over to the Project Server team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by efrene** [comment]
Resolved. Thanks for noting this!
