### ISSUE TITLE
Office 365 User access to Project for the web and Roadmap

### ISSUE THREAD

**Issue by sysadm216** [MicrosoftDocs/OfficeDocs-ProjectServer#156]
## Describe the bug

User assigned Project for Office (Plan E3) is unable to update the task progress or “% complete” of a task assigned to them in any project they have permissions to.

When clicking the link to to the task progress they get an error message "No Project subscription found"

## Expected behavior

The user with a Project for Office (Plan E3) license should be able to update their “% complete” of a task assigned to them
## Current behavior

User gets this error message

![image](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/assets/108537002/dad6a87d-6253-4d2a-bb17-f58fb296f31c)

## Possible solution

Assign Project Plan 1 license to user

## Steps to reproduce

1. Have a user licensed with a Plan 1 license create a new Project
2. Share the project with a M365 group
3. Add a user with just a Project for Office (Plan E3) license to the M365 group
4. Assign a task to the user with the Project for Office (Plan E3) license
5. Have the user with the Project for Office (Plan E3) license click the link in the email they received to the task

## Context

We want to use Project to track tasks and we do not want to assign Plan 1 licenses to all users when the documentations states a Project for Office (Plan X) license should be sufficient to update "% complete" of task.

We have opened Microsoft support ticket 2306140040005786 and the agent assigned is able to reproduce this, is this expected behavior and is the documentation is incorrect?

Is there a way to update a  “% complete” of a task with just the Project for Office (Plan X) license?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sysadm216** [comment]
@scanum  I have had a ticket open for 14 days now and still no resolution
