### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cme0848** [MicrosoftDocs/OfficeDocs-ProjectServer#16]
It is not clear on this page if when you add people to a project they are required to have a license and if so, what type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee64883-0d1b-49b9-df77-36c30c54ba35
* Version Independent ID: d1a2df1d-91b0-80f1-65f4-cfdbb0d34a6e
* Content: [Step 2 Add people to Project Online](https://docs.microsoft.com/en-us/projectonline/step-2-add-people-to-project-online)
* Content Source: [ProjectOnline/step-2-add-people-to-project-online.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/step-2-add-people-to-project-online.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@cme0848 Thank you for pointing out where we can improve this article. 

I am not certain on the answer about if they need a license and if so what type. Let me get this over to the Project Server team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@efrene any updates on this?

**Comment by efrene** [comment]
Thanks for the feedback on this article.   Your users will need a Project Online license to access a Project Online site.   For more information about the Project Online license types for your users, see the Project Online Service Description:  https://docs.microsoft.com/office365/servicedescriptions/project-online-service-description/project-online-service-description.  Thanks again!
