### ISSUE TITLE
Permission Management DNE

### ISSUE THREAD

**Issue by cme0848** [MicrosoftDocs/OfficeDocs-ProjectServer#18]
The 'Permission Management' section for switching between Sharepoint Permission mode and Project Server Permission modes does not exist within the PWA Settings>>Additional Server Settings screen when creating an Enterprise Project from scratch online. Perhaps addition clarification is needed on this page to tell users what configuration is needed in order for these settings to be displayed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9dbee69-1f24-c251-b7c1-ec7f8b5bb90c
* Version Independent ID: b266c53c-b2d2-744a-63ad-32edd89f23ab
* Content: [Change permission management in Project Online](https://docs.microsoft.com/en-us/projectonline/change-permission-management-in-project-online)
* Content Source: [ProjectOnline/change-permission-management-in-project-online.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/change-permission-management-in-project-online.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by ganagus** [comment]
I tried the following step to change Project permission mode in Project Online:
1. Go to Office 365 Admin Portal (https://admin.microsoft.com/AdminPortal/Home#/homepage)
2. On the left blade (menu), find Admin centers icon, hover over it to display Admin centers menu, and then select SharePoint.
3. This action will display all SharePoint site collections belong to current subscription.
4. Select the site collection which PWA is hosted (by default the one with /sites/pwa)
5. On the ribbon, find Project Web App drop down icon, click the drop down button, and select Settings.
6. There you can change the permission model from SharePoint Permission Mode to Project Permission Mode.

**Comment by lindspea** [comment]
@ganagus @cme0848 Thank you for your valued contribution in helping improve MS docs.  Just to confirm do the steps mentioned by @ganagus work?  On confirmation thereof, I will have them added to the content as soon as possible.

**Comment by lindspea** [comment]
@ganagus @cme0848 I will be updating this as soon as possible.  Thanks again for your valued contribution in helping improve MS docs.

**Comment by lindspea** [comment]
@AndreaBarr @scanum this can be closed thank you.
