### ISSUE TITLE
Add Owner alias to the commands

### ISSUE THREAD

**Issue by abrahamgr** [MicrosoftDocs/OfficeDocs-ProjectServer#22]
Add property -OwnerAlias in the following commands:
New-SPSite -ContentDatabase ContentDBName -URL SiteCollectionURL/PWASiteName -Template pwa#0 -OwnerAlias domain\user
New-SPSite -ContentDatabase PWA_Content -URL http://contoso-appsrv1/sites/PWA -Template pwa#0 -OwnerAlias domain\user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f2ec73f-dea8-fef8-aebf-a607f397fc5d
* Version Independent ID: 2f01fc66-d11d-eb95-7992-57737bcdb36b
* Content: [Deploy Project Web App with a new site collection](https://docs.microsoft.com/en-us/project/deploy-project-web-app-with-a-new-site-collection-project-server-2016)
* Content Source: [Project/deploy-project-web-app-with-a-new-site-collection-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/deploy-project-web-app-with-a-new-site-collection-project-server-2016.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@get-itips Could you please investigate this?

**Comment by get-itips** [comment]
Sure @AndreaBarr , OwnerAlias is a required parameter for New-SPSite cmdlet. So the user is right, I noticed he created a Pull Request with the needed changes that it needs to be merged.

**Comment by efrene** [comment]
I will merge the change now. Thanks so much for the feedback and verification!
