### ISSUE TITLE
The documentation doesn't provide a troubleshooting if "Project Online" is not listed in Services & Add-ins

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/OfficeDocs-ProjectServer#26]
The documentation doesn't provide a troubleshooting if "Project Online" is not listed in Services & Add-ins. I have a PWA and can access Project Home, but I don't get "Project Online" listed in Services & Add-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8e9ec2-7927-d246-16cb-70000789ee5c
* Version Independent ID: 8294f728-7d03-2cef-07fa-8c60ec81c8d5
* Content: [Turn Roadmap on or off for your organization](https://docs.microsoft.com/en-us/ProjectOnline/turn-roadmap-on-or-off)
* Content Source: [ProjectOnline/Turn-Roadmap-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/Turn-Roadmap-on-or-off.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Are you using the Microsoft 365 admin preview?  If you are, currently you won't see the Project Online settings. If this is the case, you will need to switch back to the classic experience to see the settings.   Here is a link to an article that describes how to switch back:  https://docs.microsoft.com/en-us/office365/admin/microsoft-365-admin-center-preview?view=o365-worldwide#switch-to-preview-and-back-again.   There is a note about it in the article, but maybe it needs to be more prominent.  Thanks for the feedback.

**Comment by TrutzS** [comment]
@efrene Sorry for the delay. I was on vacation. I didn't use the MS 365 admin preview.
I think there is a problem with the subscription I have. The tenant is a microsoft.demos.com CRM demo tenant and is about a month old.
It features the following subscription "Dynamics 365 Customer Engagement Plan", which in turn contains a "Project Online Service" and a "Project Online Desktop Client" license, see also image attached. Somehow this is not recognized as a proper Project license.
![subscription](https://user-images.githubusercontent.com/38720925/51101713-17bcbd80-17dc-11e9-8131-2f1f761e2191.png)

**Comment by efrene** [comment]
@TrutzS  Sorry for the delay in getting back to you on this.  Yes, I agree that it is likely an issue with the license.  I believe your Office 365 tenant needs to have a Project Online Professional or Project Online Premium license in order to see the Project Online settings to configure Roadmap.

**Comment by MyProjectExpert** [comment]
Yes, that is my first thought.  However, shouldn't Roadmap work if you only had Azure Boards?

 

Efren, did I meet you last year at the MVP summit?  You are part of the Project team, I will post a question to forum.

 

 

Sincerely

Michael Wharton, Project MVP
cell: 336-972-5741
