### ISSUE TITLE
Project Online Service Settings Missing

### ISSUE THREAD

**Issue by BryanAdvisicon** [MicrosoftDocs/OfficeDocs-ProjectServer#27]
One of my customers is using Project Online Professional for faculty but Project Online is not available as an option under Services and Add-ins.  Will Roadmap be available to Project Online Professional for faculty subscribers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8e9ec2-7927-d246-16cb-70000789ee5c
* Version Independent ID: 8294f728-7d03-2cef-07fa-8c60ec81c8d5
* Content: [Turn Roadmap on or off for your organization](https://docs.microsoft.com/en-us/ProjectOnline/turn-roadmap-on-or-off)
* Content Source: [ProjectOnline/Turn-Roadmap-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/Turn-Roadmap-on-or-off.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AdvisiconIT** [comment]
Is there any update when this will be available for Project Online Professional and Premium for faculty licenses?
