### ISSUE TITLE
SQL Server 2017 Support

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/OfficeDocs-ProjectServer#3]
SharePoint Server 2016 supports SQL Server 2017. Does Project Server 2016 support it as well? If yes, could you update this official documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9875009f-8cb5-dd00-f138-be3b7a1a3fea
* Version Independent ID: 532e4d55-ebd9-1d02-7dee-f64311826055
* Content: [Software requirements for Project Server 2016](https://docs.microsoft.com/en-us/project/software-requirements-for-project-server-2016)
* Content Source: [Project/software-requirements-for-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/software-requirements-for-project-server-2016.md)
* Service: **unspecified**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
My apologies for not seeing this sooner.  The article has been updated, and many thanks for your feedback on this article.
