### ISSUE TITLE
No PowerBI

### ISSUE THREAD

**Issue by matttdavispmp** [MicrosoftDocs/OfficeDocs-ProjectServer#35]
I think this article needs to be updated, as there is no mention of PowerBI as a reporting option.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0cc1554-ace3-1b3b-9480-81b63b0a1fae
* Version Independent ID: f4dd968a-524a-2453-d55c-e6eb9e49b026
* Content: [What reporting tools can I use with project data?](https://docs.microsoft.com/en-us/ProjectOnline/what-reporting-tools-can-i-use-with-project-data#feedback)
* Content Source: [ProjectOnline/what-reporting-tools-can-i-use-with-project-data.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/what-reporting-tools-can-i-use-with-project-data.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by lindspea** [comment]
@matttdavispmp thank you for your valuable contribution in helping improve MS docs.  I will have the team look at getting this updated soonest.

**Comment by efrene** [comment]
@mattdavispmp  Just wanted to let you know the article was updated by a contributor to include PowerBI as an option. Thanks again for your interest in our content.
