### ISSUE TITLE
translation issue

### ISSUE THREAD

**Issue by Disparaitre** [MicrosoftDocs/OfficeDocs-ProjectServer#36]
when translated into Chinese, number 2016 and 2019 has added a 'year' which is not necessary.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be1ae0d0-054d-8189-1ce2-4e35bdac4e33
* Version Independent ID: 354907b6-124d-32da-f969-fde6a05780b6
* Content: [安装和配置 Project Server 2016 或 2019](https://docs.microsoft.com/zh-cn/project/install-and-configure-project-server-2016#feedback)
* Content Source: [Project/install-and-configure-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/install-and-configure-project-server-2016.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by lindspea** [comment]
@Disparaitre thank you for pointing this out.  I'll get it over to the translation team to correct. @OfficeGlobal please can you rectify.

**Comment by OfficeGlobal** [comment]
@MollyMalone Since this topic is Machine Translated and the proposed change is nice-to-have and does not have negative impact on end user, we recommend to keep the topics as it is. Please let us know if you prefer Human Translation instead.

**Comment by MollyMalone** [comment]
@OfficeGlobal I agree with your assessment.  @Disparaitre thank you for reporting it but we won't fix this one as we don't expect machine translated articles to be perfect, they just need to be understandable.

**Comment by MollyMalone** [comment]
@AndreaBarr this issue can be closed.
