### ISSUE TITLE
Edit local (specific project) custom field using CSOM

### ISSUE THREAD

**Issue by marcosbabu** [MicrosoftDocs/OfficeDocs-ProjectServer#41]
Is there a way to edit local (specific project) custom field using CSOM? Found samples to read this information using CSOM here
https://github.com/OfficeDev/Project-CSOM-Read-Local-CustomFields

But couldn't find a way to edit those fields through CSOM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 773edf6b-2061-e8d3-5136-b9bd475b465e
* Version Independent ID: 4d7bb1d4-28cf-ad7e-8765-d26ae9040bbd
* Content: [Add or edit enterprise custom fields in Project Server](https://docs.microsoft.com/en-us/project/add-or-edit-enterprise-custom-fields-in-project-server#feedback)
* Content Source: [Project/add-or-edit-enterprise-custom-fields-in-project-server.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/add-or-edit-enterprise-custom-fields-in-project-server.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@marcosbabu - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
