### ISSUE TITLE
Project Server 2013 with Project Professional 2019

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/OfficeDocs-ProjectServer#42]
Does Project Server 2013 support Project Professional 2019 (perpetual, not online version)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f92e562-1988-f679-6b97-2c220d5e47ee
* Version Independent ID: f411804d-56a4-c746-c699-36a800e3183a
* Content: [Hardware and software requirements for Project Server 2013](https://docs.microsoft.com/en-us/project/hardware-and-software-requirements-for-project-server-2013)
* Content Source: [Project/hardware-and-software-requirements-for-project-server-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/hardware-and-software-requirements-for-project-server-2013.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
@rasldasl - Thanks so much for your interest in our content.  I believe Project Server 2013 only supports client connectivity through Project Professional 2013 and Project Professional 2016.  It used to support connectivity through the Project Online Desktop Client (subscription-based desktop client via a Project Online Professional or Project Online Premium license), but this ended in September of 2018. Thanks again!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@rasldasl Hi! We understand this issue has been solved. Please feel free to reopen if you opine otherwise. We really appreciate you contributing to the docs, thanks for your feedback!

**Comment by scanum** [comment]
@officedocsbot close
