### ISSUE TITLE
Project Server 2016 database

### ISSUE THREAD

**Issue by Memoi** [MicrosoftDocs/OfficeDocs-ProjectServer#43]
Hi,

thanks to remove this line "Project Server 2016 database" at this [step](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/upgrading-to-project-server-2019.md#copy-and-move-your-databases) because there is no more Project Server DB in SP 2016 but only a Project Content DB.

**Comment by scanum** [comment]
@Memoi Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by efrene** [comment]
Thanks so much for the suggested update!
