### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-ProjectServer#45]
There is an invalid link in an article

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/Project/periodic-tasks-for-project-server-administrators
2. Search for "Brooks White"
3. click on the link

**Actual results**:
Link redirects to an non existing page
**Expected results**:
Link should redirect to an existing page

**GH Article**:
https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer-pr/blob/live/Project/periodic-tasks-for-project-server-administrators.md

![image](https://user-images.githubusercontent.com/47977325/59269831-3a021c80-8c50-11e9-8cc5-7273e85a3ec1.png)

**Comment by lindspea** [comment]
@OfficeGlobal I've checked the link and it comes up correctly.  Please confirm if you are still unable to access the link.

**Comment by OfficeGlobal** [comment]
Hello @lindspea , we're getting an error page. 
Maybe it's because we're not members of LinkedIn

![image](https://user-images.githubusercontent.com/47977325/59994674-0a421400-9655-11e9-8352-b96fe69eb8ab.png)

**Comment by lindspea** [comment]
@OfficeGlobal yes, that would be the case.  I can access it as I have a LinkedIn account.  I'll add a note mentioning that you need a LinkedIn account to access the profile.

**Comment by efrene** [comment]
Thanks for catching this and the suggested update.
