### ISSUE TITLE
Can we have a guide which reflects the entire environment TODAY. 

### ISSUE THREAD

**Issue by sladepb** [MicrosoftDocs/OfficeDocs-ProjectServer#47]
This guide, whilst dated 15 May 2019, does not reflect the Sharepoint 365 administration environment we are working with TODAY. It would be really nice to have an end to end guide for deploying new projects, with a Sharepoint site in Office365 that reflects the Office365 environment that we have today. For example, how does one create and manage a content database today (22 Jun 2019). How does one build a new top level collection TODAY when all of these elements have been removed from the Sharepoint administration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f2ec73f-dea8-fef8-aebf-a607f397fc5d
* Version Independent ID: 2f01fc66-d11d-eb95-7992-57737bcdb36b
* Content: [Deploy Project Web App with a new site collection](https://docs.microsoft.com/en-us/Project/deploy-project-web-app-with-a-new-site-collection-project-server-2016#feedback)
* Content Source: [Project/deploy-project-web-app-with-a-new-site-collection-project-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/deploy-project-web-app-with-a-new-site-collection-project-server-2016.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Thanks so much for your feedback on the content.  I noticed that the comment was for a Project Server article, but you were referencing SharePoint Office 365 administration, so I was assuming you were referring to Project Online.  If you haven't found it already, much of the content for Project Online can be found [here](https://docs.microsoft.com/en-us/projectonline/project-online).

Thanks again for noting the needed update, as we are in the process of updating some of the Project Online articles exactly for this.  We hope to get these available in July.  

Again, thanks for your interest in the content.

**Comment by scanum** [comment]
@sladepb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
