### ISSUE TITLE
Project 2013 windows service permissions and requirements

### ISSUE THREAD

**Issue by rfalkenberg** [MicrosoftDocs/OfficeDocs-ProjectServer#49]
This page does not include information about the Project Server Calculation, Events and Queue windows services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c8105f-6626-41b4-da24-9db1bafc5ea7
* Version Independent ID: f4e7ee10-3449-dc86-6db3-d47ffdfb3bfb
* Content: [Plan for administrative and service accounts in Project Server 2013](https://docs.microsoft.com/en-us/project/plan-for-administrative-and-service-accounts-in-project-server-2013-beta-2#feedback)
* Content Source: [Project/plan-for-administrative-and-service-accounts-in-project-server-2013-beta-2.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/plan-for-administrative-and-service-accounts-in-project-server-2013-beta-2.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@rfalkenberg Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@rfalkenberg thank you for reaching out and helping to improve MS Docs. Do you have any known links that I could add to the article, otherwise I will do some research to find the relevant links.

**Comment by scanum** [comment]
@rfalkenberg  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
