### ISSUE TITLE
Naming convention bug?

### ISSUE THREAD

**Issue by wobailey** [MicrosoftDocs/OfficeDocs-ProjectServer#5]
I have two stages "2 - Implementation" and "2 - Implementation - NBI" … each is used in a separate workflow.  However, my workflow using 2 - Implementation has picked up the 2 - Implementation - NBI stage somehow and will not let me select the intended 2 - Implementation stage.  This is a bug 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5410984-75f1-cd6c-353b-f6d8c7457715
* Version Independent ID: 8819df4b-1fb4-a8b4-2a15-acac18f114aa
* Content: [Best practices for creating phases and stages](https://docs.microsoft.com/en-us/projectonline/best-practices-for-creating-phases-and-stages)
* Content Source: [ProjectOnline/best-practices-for-creating-phases-and-stages.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/best-practices-for-creating-phases-and-stages.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by AndreaBarr** [comment]
@wobailey  - thank you for submitting feedback. 

Thanks for finding this potential bug. Thank you for your efforts. Support will be able to handle this case and escalate it to resolution. I want to make sure this gets resolved and the issues in GitHub are for the documents. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
