### ISSUE TITLE
Page out of date

### ISSUE THREAD

**Issue by iarch1** [MicrosoftDocs/OfficeDocs-ProjectServer#52]
I believe that the instructions on this page no longer match the options available on the sharepoint admin center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88e71a4-f3d9-045a-d3cf-878b9d375f07
* Version Independent ID: fa6cd963-95ea-d077-ba32-35396e64df3a
* Content: [Add Project Online to a site collection](https://docs.microsoft.com/en-us/projectonline/add-project-online-to-a-site-collection#feedback)
* Content Source: [ProjectOnline/add-project-online-to-a-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/add-project-online-to-a-site-collection.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@iarch1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
Please resolve issue issue before copy editing can be donel

**Comment by efrene** [comment]
This has been updated for the new SharePoint admin center UI.  Thanks!

**Comment by scanum** [comment]
@iarch1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
