### ISSUE TITLE
Setting and Roadmap missing

### ISSUE THREAD

**Issue by ericmichaelclark** [MicrosoftDocs/OfficeDocs-ProjectServer#53]
there is a post indicating that roadmaps are on by default now. I logged into my Project Online portal and saw the option to create a roadmap, and clicking on it was presented with an error that I had no Project Online license. I am licensed with Project Online Professional for faculty and have no problem standing up PWA instances or projects. Following these instructions there are no options under admin for Project Online settings. In fact, "Services & Add-ins" no longer is a menu option either indicating these instructions are out of date? Does this setting option even exist or has this been moved to an admin center I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8e9ec2-7927-d246-16cb-70000789ee5c
* Version Independent ID: 8294f728-7d03-2cef-07fa-8c60ec81c8d5
* Content: [Turn Roadmap on or off for your organization](https://docs.microsoft.com/en-us/ProjectOnline/turn-roadmap-on-or-off#feedback)
* Content Source: [ProjectOnline/Turn-Roadmap-on-or-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/Turn-Roadmap-on-or-off.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Thank you for your interest in the content.  I checked on this, and Roadmap is currently not available in any of the EDU licenses (Project Online Professional for Faculty, Project Online Premium for Faculty, Project Online Professional for Students, Project Online Premium for Students).  I'll make sure to update the article to include this. Sorry for the inconvenience.

**Comment by ericmichaelclark** [comment]
Thanks for the quick response. Is it going to be made available to EDU eventually? This would be a huge benefit to my organization.

**Comment by efrene** [comment]
I am not aware of any public announcement, so I am not sure.  One thing you can do it post this as an ask in Project User Voice. I know the product team takes a good look at all requests. The URL is https://microsoftproject.uservoice.com/forums/914203-project.  Sorry I couldn't be more help.

**Comment by scanum** [comment]
@ericmichaelclark Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
