### ISSUE TITLE
Number of PWA sites per tenant

### ISSUE THREAD

**Issue by MelvinD007** [MicrosoftDocs/OfficeDocs-ProjectServer#55]
Can we include the fact that the number PWA sites within a tenant is the same the maximum number of SharePoint Site Collections allowed in a tenant.  Chris Boyd mentioned this a while back on yammer in this thread: https://www.yammer.com/microsoft.com/threads/754680714 .  SharePoint Online limits are documented here: https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits

**Comment by scanum** [comment]
@MelvinD007 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MelvinD007 Thank you for reaching out and helping improve MS Docs.  Please can you specify which article you are referring to where you would like the limits added.

**Comment by MelvinD007** [comment]
The article where we could add this information to is this one: Project Online: software boundaries and limits: https://docs.microsoft.com/en-us/projectonline/project-online-software-boundaries-and-limits


Thanks,
Melvin

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by MelvinD007** [comment]
Hi all,
   Just checking it does not look like the article was modified.  Was it decided not to document how many PWA sites we allow per tenant in this article<https://docs.microsoft.com/en-us/projectonline/project-online-software-boundaries-and-limits>?

Thanks,
Melvin

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@MelvinD007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
