### ISSUE TITLE
The Important Note should be updated to clarify "Classic Team Site"

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-ProjectServer#59]
The Important Note should be updated to clarify "Classic Team Site"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88e71a4-f3d9-045a-d3cf-878b9d375f07
* Version Independent ID: fa6cd963-95ea-d077-ba32-35396e64df3a
* Content: [Add Project Online to a site collection](https://docs.microsoft.com/en-us/projectonline/add-project-online-to-a-site-collection)
* Content Source: [ProjectOnline/add-project-online-to-a-site-collection.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/add-project-online-to-a-site-collection.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by Marweis** [comment]
And that the site must have originated in SPO (as migrated sites may or may not pass validation checks) and that the template specified at creation time is a support type (rather than the custom, select template later option).

**Comment by scanum** [comment]
@Marweis Thanks for submitting feedback, we are investigating this issue.

**Comment by j0rt3g4** [comment]
Solved on PR #61

**Comment by scanum** [comment]
@Marweis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
