### ISSUE TITLE
A bit unclear on the licensing

### ISSUE THREAD

**Issue by AnatolN** [MicrosoftDocs/OfficeDocs-ProjectServer#60]
We have 2 phrases in the article that are a bit contradictory: "Any interaction on a Project Site requires a Project Online license." and " They can still work with documents, issues, and risks, but won't be able to manage projects or work with time sheets until they have a Project Online license.". Would that translate into "Some interactions on the site require licenses"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c299de5a-991a-d872-cbc6-af33828a5e6a
* Version Independent ID: 0f177d91-00c4-2128-475c-e63c4e37972c
* Content: [Using Project Online with external users](https://docs.microsoft.com/en-us/projectonline/using-project-online-with-external-users)
* Content Source: [ProjectOnline/using-project-online-with-external-users.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/using-project-online-with-external-users.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@AnatolN  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@AnatolN 
Basically they aren't contradictory.
To create a project site You'll need a Project Professional License.
To work as coworker in a project you need a Project Essential License.

This means that you would need to interact with project Online sites a valid license 
"Any interaction on a Project Site requires a Project Online license."  (CORRECT)

> "They can still work with documents, issues, and risks, but won't be able to manage projects or work with timesheets until they have a Project Online license.". Would that translate into "Some interactions on the site require licenses"?

Not at all, this means that you're in the supposed that you're inviting a "guest" to your Project Online Site, so he/she would need to accept the invitation so you can add the license required for this access, if it's essentials would be a "member of the project" and if the license you assign is professional It'd be a manager or have admin rights over the Project Online Site.

Added information on PR #62

**Comment by scanum** [comment]
@AnatolN Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
