### ISSUE TITLE
Impossible to open Project Online settings and to turn on Roadmap on my organization 

### ISSUE THREAD

**Issue by efanicole** [MicrosoftDocs/OfficeDocs-ProjectServer#63]
Hello, 
I open my Microsoft 365 Admin Center. Then I click Services & Add-ins under Settings. I can see a line with Project Online. But when I click on it, I have an error message. The message says : 
“Something’s wrong and we can’t load this page. Refresh and try.” 
Could you tell me why I can’t open this page and how can I resolve this problem? 
Thank you for your help

**Comment by efrene** [comment]
@efanicole, for this issue I would suggest you open a support case.  Thanks and sorry for the delayed response.
