### ISSUE TITLE
License Usage

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-ProjectServer#64]
how can a global admin determine which user are not using an assigned License?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 129e6c4a-03f2-9a84-cecd-14adf3e490b2
* Version Independent ID: 65a3bb77-a63e-7375-5dbe-47c50b236cb6
* Content: [Periodic tasks for Project Online administrators](https://docs.microsoft.com/en-us/projectonline/periodic-tasks-for-project-online-administrators)
* Content Source: [ProjectOnline/periodic-tasks-for-project-online-administrators.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectOnline/periodic-tasks-for-project-online-administrators.md)
* Service: **project-online**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @DeanGross, thank you for your feedback.

Please check these reports:
https://docs.microsoft.com/en-us/office365/admin/usage-analytics/active-user-in-usage-reports

**Comment by DeanGross** [comment]
Thanks but there is nothing on that page for the Project Online application.

**Comment by dariomws306** [comment]
Please check Office activation report on that page:
"Any user who has activated their Office 365 Pro Plus, Visio Pro or Project Pro subscription on at least one device."

**Comment by scanum** [comment]
@DeanGross Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
