### ISSUE TITLE
Project Server 2016

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-ProjectServer#65]
I believe this also applies to Project Server/on-prem 2016. Can the article be updated to indicate it applies to 2013 and 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5daab037-dd0d-bdd8-82f9-b3a935f23570
* Version Independent ID: d6c998aa-ddc8-acde-9f2d-f0e0b9114a98
* Content: [Default group permissions in Project Server 2013](https://docs.microsoft.com/en-us/project/default-group-permissions-in-project-server-2013#feedback)
* Content Source: [Project/default-group-permissions-in-project-server-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/Project/default-group-permissions-in-project-server-2013.md)
* Product: **project-server-itpro**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @SharePointBlackBelt, thank your for your feedback.

I think it's the Project Server 2016 permissions article:
https://docs.microsoft.com/project/plan-groups-categories-and-rbs-in-project-server

**Comment by scanum** [comment]
@SharePointBlackBelt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
