### ISSUE TITLE
license management

### ISSUE THREAD

**Issue by funzel1** [MicrosoftDocs/OfficeDocs-ProjectServer#66]
Missing what you have to do   if you will allow only Project for web  (the new approach) and not Project Online (the old way using PWA instances)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0995559d-622b-c2d1-3133-9cf267de4a65
* Version Independent ID: b21ea8a9-c3fa-9cf5-ae66-58ac96cf1f6d
* Content: [Turn off Project for the web for users in your organization](https://docs.microsoft.com/en-us/project-for-the-web/turn-project-for-the-web-off)
* Content Source: [ProjectWeb/turn-project-for-the-web-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/turn-project-for-the-web-off.md)
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
If you want only Project for the web, but not Project Online or Roadmap, you can get the Project Plan 1 license.  If you want Project for the web and Roadmap, you would need either the Project Plan 3 or Plan 5 license, but you would have to disable the Project Online service for the user.   I updated the article with information on how to do this.  Thanks!

**Comment by scanum** [comment]
@funzel1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
