### ISSUE TITLE
Clarification or better wording around AAD

### ISSUE THREAD

**Issue by ferrety2006** [MicrosoftDocs/OfficeDocs-ProjectServer#67]
"While any user in Azure Active Directory (AAD) is automatically available as a resource to assign to project tasks in Project for the web, you need to manually add non-user resources."

I tested added a B2B guest to a project task, but it was not successful. I could be doing something incorrectly of course, but I think it'd be very helpful if the quoted sentence clarified if "...any user in Azure Active Directory..." really is 'any' user since B2B guests are users in AAD, too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447f59e5-5797-453e-1104-8645a39230a6
* Version Independent ID: f7400ea9-2c87-d96a-6cd4-3b1882372e4e
* Content: [Add non-user resources in Project for the web - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/create-nonuser-resources-in-project-for-the-web)
* Content Source: [ProjectWeb/create-nonuser-resources-in-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/create-nonuser-resources-in-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@ferrety2006 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ferrety2006 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
