### ISSUE TITLE
Make sure that you are browsing your default D365 instance

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/OfficeDocs-ProjectServer#71]
When going to the D365 Admin settings. Be sure that you are going to the default instance URL. Otherwise you will not be able to find the projects listed in Project on the Web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4f1adb3-b824-60a4-e21f-616feec2270d
* Version Independent ID: 5dc9a015-0485-4d8a-d31e-8af06dcb4dde
* Content: [Access a project in Project for the web after its Office 365 group has been deleted - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/access-a-project-after-group-is-deleted)
* Content Source: [ProjectWeb/access-a-project-after-group-is-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/access-a-project-after-group-is-deleted.md)
* Service: ****
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@SLeuthold Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@SLeuthold thank you for helping improve MS Docs. This article has been updated in the interim to read correctly. Thanks again for your help. @scanum this can be closed thank you.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@SLeuthold Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
