### ISSUE TITLE
Office 365 Group / Team not showing up in drop down selection for existing group option

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/OfficeDocs-ProjectServer#72]
The UI appears to be truncating a list of O365 groups when you have "many" in a tenant. In addition, the UI should have the ability to search, especially in organizations that have "many" O365 groups. I'll add to uservoice.... eventually :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4f1adb3-b824-60a4-e21f-616feec2270d
* Version Independent ID: 5dc9a015-0485-4d8a-d31e-8af06dcb4dde
* Content: [Access a project in Project for the web after its Office 365 group has been deleted - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/access-a-project-after-group-is-deleted)
* Content Source: [ProjectWeb/access-a-project-after-group-is-deleted.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/access-a-project-after-group-is-deleted.md)
* Service: ****
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Hi Stephen,
Thanks for the great feedback on this!  I’ll make sure to forward this on to engineering as well.
Thanks again!
Efren

**Comment by SLeuthold** [comment]
Great, thank you. We are excited and we are all in. Is there a cadence that we can setup with engineering?

**Comment by efrene** [comment]
Your best route to provide feedback on issues and features is UserVoice.

**Comment by scanum** [comment]
@SLeuthold Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
