### ISSUE TITLE
Project not visable under "Settings", Settings"

### ISSUE THREAD

**Issue by andreaslarssonliu** [MicrosoftDocs/OfficeDocs-ProjectServer#77]
There is no project in the admin center, and yes I have tried the new and old admin experience.
We have an education tenant if thats relevant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bee97a7-c8c3-d839-3d4c-f1b1d870fe8f
* Version Independent ID: 6b69b046-cdcf-065b-1a5a-055a46e6ebce
* Content: [Turn Project for the web or Roadmap on or off for users in your organization - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/turn-project-for-the-web-off#feedback)
* Content Source: [ProjectWeb/turn-project-for-the-web-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/turn-project-for-the-web-off.md)
* Service: ****
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Hi Andrea - Thanks for your feedback. It is likely that you EDU tenant has not been fully activated yet, as I know it is in the process of being rolled out to tenants. Please view your message center, as I think there should be a post on this.

**Comment by scanum** [comment]
@andreaslarssonliu  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
