### ISSUE TITLE
Running export script error

### ISSUE THREAD

**Issue by HyperionCruiser** [MicrosoftDocs/OfficeDocs-ProjectServer#79]
Downloads\ExportProjectContent&gt; ExportProjectContent -ProjectID 33a6c371-1bb0-4049-ac21-f5aa0331b54c -OutputDirectory C:\project -InstanceId https://org3c4d8b03.crm3.dynamics.com/
Starting Project Client
ExportProjectContent : The property 'GlobalAssemblyCache' cannot be found on this object. Verify that the property
exists.
At line:1 char:1
+ ExportProjectContent -ProjectID 33a6c371-1bb0-4049-ac21-f5aa0331b54c  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ExportProjectContent], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,ExportProjectContent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c839da-0f06-c409-9744-4d285e405dbb
* Version Independent ID: 161f4096-13a0-1368-bdbd-0e530bcffbf0
* Content: [Export user data from Project for the Web - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/export-user-data-from-project-for-the-web)
* Content Source: [ProjectWeb/export-user-data-from-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/export-user-data-from-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by scanum** [comment]
@HyperionCruiser thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
