### ISSUE TITLE
How to assign Office 365 users view only access to Project for the Web and Roadmap

### ISSUE THREAD

**Issue by jvburns** [MicrosoftDocs/OfficeDocs-ProjectServer#83]
This article is clear about who is able to have view only access but not how to provide them view only access.  From the article - "However, users that are assigned certain Office 365 licenses are allowed to have view access to Project for the web and Roadmap. This will allow them to have read-only access to projects and roadmaps that are shared with them, without needing to be assigned a Project Plan license."  I have a user with a listed license, I tried adding them to the Project as a team member, but they still cannot view the project.  

How is access to be provided?

**Comment by efrene** [comment]
Thank you so much for viewing the content. I just wanted to verify a few things. I'm assuming your use is able to be successfully added to the group, and is able to see the project listed in the "Shared with me" tab on the Project Home page.   When they click on it, what do they see?  Do they get a "No Project subscription found" message?  Thanks.

**Comment by scanum** [comment]
@jvburns We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
