### ISSUE TITLE
Instructions not working as described.

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/OfficeDocs-ProjectServer#85]
[So Project just showed up for all staff as a menu Option although we don't use it and have no licenses. Tried to follow these instructions to turn off for all BUT. No project option exists under Settings-Org Settings. For Users Licensing, no option exists for Project. Looks like MS released this to end users but have not updated Office365-Admin to manage it :( Please update instructions that work, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bee97a7-c8c3-d839-3d4c-f1b1d870fe8f
* Version Independent ID: 6b69b046-cdcf-065b-1a5a-055a46e6ebce
* Content: [Turn Project for the web or Roadmap on or off for users in your organization - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/turn-project-for-the-web-off)
* Content Source: [ProjectWeb/turn-project-for-the-web-off.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/turn-project-for-the-web-off.md)
* Service: ****
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
Thanks for your feedback on the content.  It sounds like it is possible that your users Office 365 or Microsoft 365 licenses were ones that now allow read access to Project for the web or roadmaps.  [See this article](https://docs.microsoft.com/en-us/project-for-the-web/office-365-user-view-access-to-project-and-roadmap).  You might have received a message center post on that.  You can remove the Project icon from your users app launcher through instructions [in this article](https://docs.microsoft.com/en-us/project-for-the-web/remove-project-from-the-office-365-app-launcher).  Sorry for the inconvenience, and hope this helps.

**Comment by kcnighsurf** [comment]
I’d tried that also. ‘Project for Office’ doesn’t exist under licenses and apps.

**Comment by efrene** [comment]
I would suggest opening a support ticket at this point, especially if you are seeing the Project tile, your users have licenses in which they have view access to Project for the web and roadmap, and you aren't able to see  "Project for Office".  Again, sorry for the inconvenience.
