### ISSUE TITLE
Can you please add an additional explanation as to why you can create a resource but can't edit or delete it?  Thanks.

### ISSUE THREAD

**Issue by jason-collab** [MicrosoftDocs/OfficeDocs-ProjectServer#87]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447f59e5-5797-453e-1104-8645a39230a6
* Version Independent ID: f7400ea9-2c87-d96a-6cd4-3b1882372e4e
* Content: [Add non-user resources in Project for the web - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/create-nonuser-resources-in-project-for-the-web)
* Content Source: [ProjectWeb/create-nonuser-resources-in-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/create-nonuser-resources-in-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by sayedpfe** [comment]
Hello 

I believe you can edit or delete resources from Resources page as the below screen 
![image](https://user-images.githubusercontent.com/13697878/91212778-5a18e100-e719-11ea-9a2a-788dd6100d7d.png)


did i understand your question correctly ?

**Comment by scanum** [comment]
@jason-collab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jason-collab** [comment]
Yes, it has been resolved.  However, after talking to a Microsoft associate on the phone about the issue, I had to request access from my D365 admin in order to edit or delete resources I created.  That is not stated anywhere on the document page.  I did not have that ability just because I had a Project for the Web/Project Online license.  I only have a create permission through that license.  So, that may be something you want to explain a bit on your documentation page.

Thanks for the follow-up.


Jason Hughes
Systems Analyst
The Greenheck Group
715-355-2258 Office

715-432-7867 Mobile
jason.hughes@greenheck.com<mailto:jason.hughes@greenheck.com>

________________________________
