### ISSUE TITLE
Which CDS Entity has Resource master ? 

### ISSUE THREAD

**Issue by parthrawal** [MicrosoftDocs/OfficeDocs-ProjectServer#98]
I need to know resource master which Project for the web refers to. As "msdyn_resourceassignments" has several id which refer to resources. I am unable to identify how to map resource id/owner id without master data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c839da-0f06-c409-9744-4d285e405dbb
* Version Independent ID: 161f4096-13a0-1368-bdbd-0e530bcffbf0
* Content: [Export user data from Project for the Web - Project for the web](https://docs.microsoft.com/en-us/project-for-the-web/export-user-data-from-project-for-the-web)
* Content Source: [ProjectWeb/export-user-data-from-project-for-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-ProjectServer/blob/live/ProjectWeb/export-user-data-from-project-for-the-web.md)
* Service: **project-web**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@parthrawal Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
